//
// Generated by CocoaPods-Keys
// on 23/09/2016
// For more information see https://github.com/orta/cocoapods-keys
//

#import <Foundation/NSString.h>

@interface BuildasaurxcodeprojKeys : NSObject

- (NSString *)gitHubAPIClientId;
- (NSString *)gitHubAPIClientSecret;
- (NSString *)enterpriseGitHubHostname;
- (NSString *)enterpriseGitHubAPIPath;
- (NSString *)enterpriseGitHubAPIClientId;
- (NSString *)enterpriseGitHubAPIClientSecret;
- (NSString *)bitBucketAPIClientId;
- (NSString *)bitBucketAPIClientSecret;

@end
